// Code generated by "stringer -type=NodeKind -output nodekind_string.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeModule-0]
	_ = x[NodeAssign-1]
	_ = x[NodeAugAssign-2]
	_ = x[NodeName-3]
	_ = x[NodeNumber-4]
	_ = x[NodeString-5]
	_ = x[NodeBinOp-6]
	_ = x[NodeUnaryOp-7]
	_ = x[NodeCall-8]
	_ = x[NodeAttribute-9]
	_ = x[NodeCompare-10]
	_ = x[NodeCompareOp-11]
	_ = x[NodeBooleanOp-12]
	_ = x[NodeBoolean-13]
	_ = x[NodeTuple-14]
	_ = x[NodeNone-15]
	_ = x[NodeList-16]
	_ = x[NodeIf-17]
	_ = x[NodeFor-18]
	_ = x[NodeWhile-19]
	_ = x[NodeReturn-20]
	_ = x[NodePass-21]
	_ = x[NodeBreak-22]
	_ = x[NodeContinue-23]
	_ = x[NodeFunctionDef-24]
	_ = x[NodeClassDef-25]
	_ = x[NodeExprStmt-26]
	_ = x[NodeBlock-27]
	_ = x[NodeArgs-28]
	_ = x[NodeErrExp-29]
	_ = x[NodeSubScript-30]
	_ = x[NodeBaseList-31]
	_ = x[NodeErrStmt-32]
	_ = x[NodeParam-33]
	_ = x[NodeImport-34]
	_ = x[NodeFromImport-35]
	_ = x[NodeAlias-36]
	_ = x[NodeSlice-37]
	_ = x[NodeKeywordArg-38]
	_ = x[NodeDict-39]
	_ = x[NodeAnnAssign-40]
	_ = x[NodeTry-41]
	_ = x[NodeExcept-42]
	_ = x[NodeListComp-43]
	_ = x[NodeComprehension-44]
}

const _NodeKind_name = "NodeModuleNodeAssignNodeAugAssignNodeNameNodeNumberNodeStringNodeBinOpNodeUnaryOpNodeCallNodeAttributeNodeCompareNodeCompareOpNodeBooleanOpNodeBooleanNodeTupleNodeNoneNodeListNodeIfNodeForNodeWhileNodeReturnNodePassNodeBreakNodeContinueNodeFunctionDefNodeClassDefNodeExprStmtNodeBlockNodeArgsNodeErrExpNodeSubScriptNodeBaseListNodeErrStmtNodeParamNodeImportNodeFromImportNodeAliasNodeSliceNodeKeywordArgNodeDictNodeAnnAssignNodeTryNodeExceptNodeListCompNodeComprehension"

var _NodeKind_index = [...]uint16{0, 10, 20, 33, 41, 51, 61, 70, 81, 89, 102, 113, 126, 139, 150, 159, 167, 175, 181, 188, 197, 207, 215, 224, 236, 251, 263, 275, 284, 292, 302, 315, 327, 338, 347, 357, 371, 380, 389, 403, 411, 424, 431, 441, 453, 470}

func (i NodeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeKind_index)-1 {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[idx]:_NodeKind_index[idx+1]]
}
