// Code generated by "stringer -type=NodeKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeModule-0]
	_ = x[NodeAssign-1]
	_ = x[NodeAugAssign-2]
	_ = x[NodeName-3]
	_ = x[NodeNumber-4]
	_ = x[NodeString-5]
	_ = x[NodeBytes-6]
	_ = x[NodeFString-7]
	_ = x[NodeFStringText-8]
	_ = x[NodeFStringExpr-9]
	_ = x[NodeBinOp-10]
	_ = x[NodeUnaryOp-11]
	_ = x[NodeCall-12]
	_ = x[NodeAttribute-13]
	_ = x[NodeCompare-14]
	_ = x[NodeCompareOp-15]
	_ = x[NodeBooleanOp-16]
	_ = x[NodeBoolean-17]
	_ = x[NodeTuple-18]
	_ = x[NodeNone-19]
	_ = x[NodeList-20]
	_ = x[NodeIf-21]
	_ = x[NodeFor-22]
	_ = x[NodeWhile-23]
	_ = x[NodeAssert-24]
	_ = x[NodeDel-25]
	_ = x[NodeGlobal-26]
	_ = x[NodeNonlocal-27]
	_ = x[NodeReturn-28]
	_ = x[NodeYield-29]
	_ = x[NodeRaise-30]
	_ = x[NodePass-31]
	_ = x[NodeBreak-32]
	_ = x[NodeContinue-33]
	_ = x[NodeFunctionDef-34]
	_ = x[NodeClassDef-35]
	_ = x[NodeExprStmt-36]
	_ = x[NodeBlock-37]
	_ = x[NodeArgs-38]
	_ = x[NodeErrExp-39]
	_ = x[NodeSubScript-40]
	_ = x[NodeBaseList-41]
	_ = x[NodeErrStmt-42]
	_ = x[NodeParam-43]
	_ = x[NodeImport-44]
	_ = x[NodeFromImport-45]
	_ = x[NodeAlias-46]
	_ = x[NodeSlice-47]
	_ = x[NodeKeywordArg-48]
	_ = x[NodeStarArg-49]
	_ = x[NodeKwStarArg-50]
	_ = x[NodeDict-51]
	_ = x[NodeAnnAssign-52]
	_ = x[NodeTry-53]
	_ = x[NodeExcept-54]
	_ = x[NodeListComp-55]
	_ = x[NodeDictComp-56]
	_ = x[NodeGeneratorExp-57]
	_ = x[NodeConditional-58]
	_ = x[NodeComprehension-59]
	_ = x[NodeWith-60]
	_ = x[NodeWithItem-61]
	_ = x[NodeDecorator-62]
}

const _NodeKind_name = "NodeModuleNodeAssignNodeAugAssignNodeNameNodeNumberNodeStringNodeBytesNodeFStringNodeFStringTextNodeFStringExprNodeBinOpNodeUnaryOpNodeCallNodeAttributeNodeCompareNodeCompareOpNodeBooleanOpNodeBooleanNodeTupleNodeNoneNodeListNodeIfNodeForNodeWhileNodeAssertNodeDelNodeGlobalNodeNonlocalNodeReturnNodeYieldNodeRaiseNodePassNodeBreakNodeContinueNodeFunctionDefNodeClassDefNodeExprStmtNodeBlockNodeArgsNodeErrExpNodeSubScriptNodeBaseListNodeErrStmtNodeParamNodeImportNodeFromImportNodeAliasNodeSliceNodeKeywordArgNodeStarArgNodeKwStarArgNodeDictNodeAnnAssignNodeTryNodeExceptNodeListCompNodeDictCompNodeGeneratorExpNodeConditionalNodeComprehensionNodeWithNodeWithItemNodeDecorator"

var _NodeKind_index = [...]uint16{0, 10, 20, 33, 41, 51, 61, 70, 81, 96, 111, 120, 131, 139, 152, 163, 176, 189, 200, 209, 217, 225, 231, 238, 247, 257, 264, 274, 286, 296, 305, 314, 322, 331, 343, 358, 370, 382, 391, 399, 409, 422, 434, 445, 454, 464, 478, 487, 496, 510, 521, 534, 542, 555, 562, 572, 584, 596, 612, 627, 644, 652, 664, 677}

func (i NodeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeKind_index)-1 {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[idx]:_NodeKind_index[idx+1]]
}
