// Code generated by "stringer -type=NodeKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeModule-0]
	_ = x[NodeAssign-1]
	_ = x[NodeAugAssign-2]
	_ = x[NodeName-3]
	_ = x[NodeNumber-4]
	_ = x[NodeString-5]
	_ = x[NodeBinOp-6]
	_ = x[NodeUnaryOp-7]
	_ = x[NodeCall-8]
	_ = x[NodeAttribute-9]
	_ = x[NodeCompare-10]
	_ = x[NodeCompareOp-11]
	_ = x[NodeBooleanOp-12]
	_ = x[NodeBoolean-13]
	_ = x[NodeTuple-14]
	_ = x[NodeNone-15]
	_ = x[NodeList-16]
	_ = x[NodeIf-17]
	_ = x[NodeFor-18]
	_ = x[NodeWhile-19]
	_ = x[NodeReturn-20]
	_ = x[NodeBreak-21]
	_ = x[NodeContinue-22]
	_ = x[NodeFunctionDef-23]
	_ = x[NodeClassDef-24]
	_ = x[NodeExprStmt-25]
	_ = x[NodeBlock-26]
	_ = x[NodeArgs-27]
	_ = x[NodeErrExp-28]
	_ = x[NodeSubScript-29]
	_ = x[NodeBaseList-30]
	_ = x[NodeErrStmt-31]
	_ = x[NodeParam-32]
	_ = x[NodeImport-33]
	_ = x[NodeFromImport-34]
	_ = x[NodeAlias-35]
	_ = x[NodeSlice-36]
	_ = x[NodeKeywordArg-37]
	_ = x[NodeDict-38]
}

const _NodeKind_name = "NodeModuleNodeAssignNodeAugAssignNodeNameNodeNumberNodeStringNodeBinOpNodeUnaryOpNodeCallNodeAttributeNodeCompareNodeCompareOpNodeBooleanOpNodeBooleanNodeTupleNodeNoneNodeListNodeIfNodeForNodeWhileNodeReturnNodeBreakNodeContinueNodeFunctionDefNodeClassDefNodeExprStmtNodeBlockNodeArgsNodeErrExpNodeSubScriptNodeBaseListNodeErrStmtNodeParamNodeImportNodeFromImportNodeAliasNodeSliceNodeKeywordArgNodeDict"

var _NodeKind_index = [...]uint16{0, 10, 20, 33, 41, 51, 61, 70, 81, 89, 102, 113, 126, 139, 150, 159, 167, 175, 181, 188, 197, 207, 216, 228, 243, 255, 267, 276, 284, 294, 307, 319, 330, 339, 349, 363, 372, 381, 395, 403}

func (i NodeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeKind_index)-1 {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[idx]:_NodeKind_index[idx+1]]
}
