package lexer

var Keywords = map[string]TokenType{
	"False":    FALSE,
	"None":     NONE,
	"True":     TRUE,
	"and":      AND,
	"or":       OR,
	"not":      NOT,
	"in":       IN,
	"is":       IS,
	"if":       IF,
	"elif":     ELIF,
	"else":     ELSE,
	"for":      FOR,
	"while":    WHILE,
	"break":    BREAK,
	"continue": CONTINUE,
	"pass":     PASS,
	"def":      DEF,
	"class":    CLASS,
	"return":   RETURN,
	"import":   IMPORT,
	"from":     FROM,
	"as":       AS,
	"try":      TRY,
	"except":   EXCEPT,
	"finally":  FINALLY,
	"raise":    RAISE,
	"with":     WITH,
	"lambda":   LAMBDA,
	"assert":   ASSERT,
	"global":   GLOBAL,
	"nonlocal": NONLOCAL,
	"del":      DEL,
	"yield":    YIELD,
}
